[package]
name = "onn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
anyhow = "1.0.71"
async-trait = "0.1.68"
dotenv = "0.15.0"
futures = "0.3.28"
ndarray = "0.15.6"
ort = "1.14.8"
qdrant-client = "1.3.0"
rayon = "1.7.0"
reqwest = "0.11.18"
serde = "1.0.164"
tokenizers = "0.13.3"
openai-api-rs = {git = "https://github.com/Anush008/openai-api-rs.git", branch = "main"}
uuid = {version = "1.4.0", features = ["v4", "fast-rng"] }
zip = "0.6.6"
rust-fuzzy-search = "0.1.1"
text-splitter = "0.4.2"
